### ISSUE TITLE
UI bug 

### ISSUE THREAD

**Issue by jonasalmeida** [frlender/comut-viz#1]
React is not your friend ;-)

![Screenshot 2023-04-04 at 10 12 01 AM](https://user-images.githubusercontent.com/204769/229820463-96214e75-b4e0-4d92-a42a-475960f0cb3a.png)

**Comment by frlender** [comment]
Hi Jonas, thanks for posting an issue！Would it be possible to share your input files so that I can recreate the problem and see where it goes wrong?

**Comment by frlender** [comment]
> React is not your friend ;-)
> 
> ![Screenshot 2023-04-04 at 10 12 01 AM](https://user-images.githubusercontent.com/204769/229820463-96214e75-b4e0-4d92-a42a-475960f0cb3a.png)

Hi Jonas, thanks for posting an issue！Would it be possible to share your input files so that I can recreate the problem and see where it goes wrong?
